### ISSUE TITLE
3D Örneği

### ISSUE THREAD

**Issue by xbonds** [firatoltulu/SanalPosTR#1]
Türkiyedeki ödeme yöntemleri için hazırlanmış güzel bir kaynak olmuş. Elinize sağlık. 3D'li örnek yapamadım. Kütüphanenizi kullanabilirsem, .Net Core ile geliştirmek istiyorum.

**Comment by firatoltulu** [comment]
Selam,

Anasayfada ki örnek de 3D ile ödeme istenildiği belirtiliyor, 

Sistem şöyle çalışıyor, 3d Parametresini gönderdiğinde sistem sana bir tane html form oluşturur ve  o html formun post edilmesi beklenir.

örnek de yer alan, pay fonksiyonu eğer 3d ile ödeme ise, 

` var result = pos.Pay(payRequest); `

 result.ResultContent  de sana html formu gönderir, bu değeri aşağıdaki gibi kullanabilirsin

```

@model dynamic

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>POS Ödeme Yönlendirme</title>
</head>
<body>
	<p><strong> Lütfen Bekleyin, 3D işlemi için bankaya yönlendiriliyorsunuz </strong></p>

     @Html.Raw(Model)
     <script type="text/javascript">
         document.forms[0].submit();
     </script>
</body>
</html>

```

Bu bilgiler bankaya gittikten sonra, bankada işlem başarılı ise, vermiş olduğun URL banka değerleri post edecektir.

gelen değerleri aşağıdaki fonksiyon ile ödemeyi alabilirsin

` var   result = pos.Pay3D(payRequest, Request.Form);`

işlem yeterli olmasa test projesine eklersim sorun değil.

**Comment by xbonds** [comment]
Teşekkür ederim,

Gün içerisinde deneyeceğim.

**Comment by firatoltulu** [comment]
örnek eklendi
